# Generated by Django 4.1.1 on 2022-09-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_habitgoal_dailyrecord'),
    ]
