# Generated by Django 4.1.1 on 2022-09-11 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_habitgoal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='daily_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='records', to='habit_tracker.habitgoal'),
        ),
        migrations.AlterField(
            model_name='habitgoal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
    ]
