# Generated by Django 4.1.1 on 2022-09-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0006_alter_dailyrecord_notes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('date',), name='one_entry_daily'),
        ),
    ]
